# Generated by Django 4.0.3 on 2022-04-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('scores', models.IntegerField()),
                ('rebounds', models.IntegerField()),
                ('offensive_rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('screen_assists', models.IntegerField()),
                ('good_screens', models.IntegerField()),
                ('blockshots', models.IntegerField()),
                ('threepoints', models.IntegerField()),
                ('create_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('create_user', models.CharField(max_length=20)),
                ('update_user', models.CharField(max_length=20)),
            ],
        ),
    ]
