# Generated by Django 4.0.3 on 2022-04-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_stats_hustle_plays_stats_memo_alter_stats_assists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='create_datetime',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='update_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='update_user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
